package com.zingkg.renamer;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

public final class RenamerUI extends javax.swing.JFrame {
    private List<File> currentFiles;

    /**
     * Creates RenamerUI.
     */
    public RenamerUI() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if (args.length != 0) {
            // Command line version since there are arguments passed.
            CommandLine.main(args);
        } else {
            // UI version
            /* Set the Nimbus look and feel */
            /* <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(RenamerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            // Create and display the form
            java.awt.EventQueue.invokeLater(() -> new RenamerUI().setVisible(true));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        renameNumberButtonGroup = new javax.swing.ButtonGroup();
        prefixSuffixButtonGroup = new javax.swing.ButtonGroup();
        prefixSuffixNumberButtonGroup = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        filePreviewTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        previewFileTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        loadedFileTable = new javax.swing.JTable();
        filesOpenButton = new javax.swing.JButton();
        filesClearButton = new javax.swing.JButton();
        renameTabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        fileRenamePanel = new javax.swing.JPanel();
        fileRenameReplaceLabel = new javax.swing.JLabel();
        fileRenameTextField = new javax.swing.JTextField();
        renameAscendingRadioButton = new javax.swing.JRadioButton();
        renameDescendingRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        renameTabStartingNumber = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        prefixRadioButton = new javax.swing.JRadioButton();
        suffixRadioButton = new javax.swing.JRadioButton();
        prefixSuffixNumberCheckBox = new javax.swing.JCheckBox();
        prefixSuffixAscendingRadioButton = new javax.swing.JRadioButton();
        prefixSuffixDescendingRadioButton = new javax.swing.JRadioButton();
        fileNumberStartNumberTextField = new javax.swing.JTextField();
        fileNumberStartNumberLabel = new javax.swing.JLabel();
        fileNumberInputStringLabel = new javax.swing.JLabel();
        fileNumberInputStringTextField = new javax.swing.JTextField();
        renameButton = new javax.swing.JButton();
        previewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Renamer");

        jSplitPane1.setDividerLocation(350);

        filePreviewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "File", "Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(filePreviewTable);

        jSplitPane1.setRightComponent(jScrollPane3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));

        previewFileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File", "Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(previewFileTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Loaded Files"));

        loadedFileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File", "Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(loadedFileTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel5);

        filesOpenButton.setText("Load");
        filesOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filesOpenButtonActionPerformed(evt);
            }
        });

        filesClearButton.setText("Clear");
        filesClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filesClearButtonActionPerformed(evt);
            }
        });

        renameTabs.setToolTipText("");

        fileRenamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("File Rename"));

        fileRenameReplaceLabel.setText("Replace");

        renameNumberButtonGroup.add(renameAscendingRadioButton);
        renameAscendingRadioButton.setSelected(true);
        renameAscendingRadioButton.setLabel("Ascending");

        renameNumberButtonGroup.add(renameDescendingRadioButton);
        renameDescendingRadioButton.setLabel("Descending");

        jLabel1.setText("Starting number:");

        renameTabStartingNumber.setModel(new javax.swing.SpinnerNumberModel());
        renameTabStartingNumber.setValue(1);

        javax.swing.GroupLayout fileRenamePanelLayout = new javax.swing.GroupLayout(fileRenamePanel);
        fileRenamePanel.setLayout(fileRenamePanelLayout);
        fileRenamePanelLayout.setHorizontalGroup(
            fileRenamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileRenamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fileRenamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fileRenamePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(renameTabStartingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fileRenamePanelLayout.createSequentialGroup()
                        .addComponent(renameAscendingRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(renameDescendingRadioButton))
                    .addGroup(fileRenamePanelLayout.createSequentialGroup()
                        .addComponent(fileRenameReplaceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileRenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 477, Short.MAX_VALUE))
        );
        fileRenamePanelLayout.setVerticalGroup(
            fileRenamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileRenamePanelLayout.createSequentialGroup()
                .addGroup(fileRenamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(renameTabStartingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fileRenamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(renameAscendingRadioButton)
                    .addComponent(renameDescendingRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fileRenamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileRenameReplaceLabel)
                    .addComponent(fileRenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileRenamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileRenamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        renameTabs.addTab("Rename", jPanel1);

        prefixSuffixButtonGroup.add(prefixRadioButton);
        prefixRadioButton.setSelected(true);
        prefixRadioButton.setText("Prefix");

        prefixSuffixButtonGroup.add(suffixRadioButton);
        suffixRadioButton.setText("Suffix");

        prefixSuffixNumberCheckBox.setText("Number");
        prefixSuffixNumberCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefixSuffixNumberCheckBoxActionPerformed(evt);
            }
        });

        prefixSuffixNumberButtonGroup.add(prefixSuffixAscendingRadioButton);
        prefixSuffixAscendingRadioButton.setSelected(true);
        prefixSuffixAscendingRadioButton.setText("Ascending");
        prefixSuffixAscendingRadioButton.setEnabled(false);

        prefixSuffixNumberButtonGroup.add(prefixSuffixDescendingRadioButton);
        prefixSuffixDescendingRadioButton.setText("Descending");
        prefixSuffixDescendingRadioButton.setEnabled(false);

        fileNumberStartNumberLabel.setText("Start Number");

        fileNumberInputStringLabel.setText("Input String");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileNumberInputStringLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fileNumberStartNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileNumberInputStringTextField)
                            .addComponent(fileNumberStartNumberTextField)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(prefixSuffixNumberCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prefixSuffixAscendingRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prefixSuffixDescendingRadioButton))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(prefixRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suffixRadioButton)))
                        .addGap(0, 540, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefixRadioButton)
                    .addComponent(suffixRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefixSuffixNumberCheckBox)
                    .addComponent(prefixSuffixAscendingRadioButton)
                    .addComponent(prefixSuffixDescendingRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNumberInputStringLabel)
                    .addComponent(fileNumberInputStringTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNumberStartNumberLabel)
                    .addComponent(fileNumberStartNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        renameTabs.addTab("Prefix/ Suffix", jPanel3);

        renameButton.setText("Rename");
        renameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameButtonActionPerformed(evt);
            }
        });

        previewButton.setText("Preview");
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSplitPane1)
                    .addComponent(renameTabs)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(filesOpenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filesClearButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(previewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(renameButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filesOpenButton)
                    .addComponent(filesClearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(renameTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(renameButton)
                    .addComponent(previewButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        renameTabs.getAccessibleContext().setAccessibleName("Rename Tab");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filesOpenButtonActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filesOpenButtonActionPerformed
        // Select multiple files
        c.setMultiSelectionEnabled(true);
        final int rVal = c.showOpenDialog(RenamerUI.this);
        if (rVal == JFileChooser.APPROVE_OPTION) {
            currentFiles = Arrays.asList(c.getSelectedFiles());
            currentFiles.forEach(file -> {
                final String filePath = file.getPath();
                ((DefaultTableModel) loadedFileTable.getModel()).addRow(
                    new Object[]{file.getName(), filePath}
                );
            });
        }
    }//GEN-LAST:event_filesOpenButtonActionPerformed

    private void filesClearButtonActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filesClearButtonActionPerformed
        currentFiles = new ArrayList<>();
        eraseFileTables();
    }//GEN-LAST:event_filesClearButtonActionPerformed

    private void eraseFileTables() {
        eraseTable(loadedFileTable);
        eraseTable(previewFileTable);
    }

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
        eraseTable(previewFileTable);

        Stream<String> filePaths = getFilePathList();
        runFileOperation(filePaths).map(file -> {
            final String fileName = file.getName();
            final String filePath = file.getAbsolutePath();
            return new Object[]{fileName, filePath};
        }).forEach(((DefaultTableModel) previewFileTable.getModel())::addRow);
    }//GEN-LAST:event_previewButtonActionPerformed

    private void renameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameButtonActionPerformed
        List<String> filePaths = getFilePathList().collect(Collectors.toList());
        Stream<File> previewFiles = runFileOperation(filePaths.stream());
        FileUtilities.renameFiles(filePaths.stream(), previewFiles);
        eraseFileTables();
    }//GEN-LAST:event_renameButtonActionPerformed

    private void prefixSuffixNumberCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefixSuffixNumberCheckBoxActionPerformed
        if (prefixSuffixNumberCheckBox.isSelected())
            setEnabledStatusOnPrefixSuffixRadioButtons(true);
        else
            setEnabledStatusOnPrefixSuffixRadioButtons(false);
    }//GEN-LAST:event_prefixSuffixNumberCheckBoxActionPerformed

    private void setEnabledStatusOnPrefixSuffixRadioButtons(boolean status) {
        prefixSuffixAscendingRadioButton.setEnabled(status);
        prefixSuffixDescendingRadioButton.setEnabled(status);
    }

    private Stream<File> runFileOperation(Stream<String> filePaths) {
        if (renameTabs.getSelectedIndex() == 0) {
            // First tab is rename.
            if (renameAscendingRadioButton.isSelected()) {
                return FileUtilities.renameAppendAsc(
                    fileRenameTextField.getText(),
                    (Integer) renameTabStartingNumber.getValue(),
                    filePaths
                );
            } else if (renameDescendingRadioButton.isSelected()) {
                return FileUtilities.renameAppendDesc(
                    fileRenameTextField.getText(),
                    (Integer) renameTabStartingNumber.getValue(),
                    filePaths
                );
            }
        } else if (renameTabs.getSelectedIndex() == 1) {
            if (prefixRadioButton.isSelected() && !prefixSuffixNumberCheckBox.isSelected()) {
                return FileUtilities.prependString(
                    fileNumberInputStringTextField.getText(),
                    filePaths
                );
            } else if (suffixRadioButton.isSelected() && !prefixSuffixNumberCheckBox.isSelected()) {
                return FileUtilities.appendString(
                    fileNumberInputStringTextField.getText(),
                    filePaths
                );
            } else if (
                prefixRadioButton.isSelected() &&
                prefixSuffixAscendingRadioButton.isSelected()
            ) {
                return FileUtilities.numberPrepend(
                    fileNumberInputStringTextField.getText(),
                    Integer.parseInt(fileNumberStartNumberTextField.getText()),
                    filePaths
                );
            } else if (
                suffixRadioButton.isSelected() &&
                prefixSuffixAscendingRadioButton.isSelected()
            ) {
                return FileUtilities.numberAppend(
                        fileNumberInputStringTextField.getText(),
                        Integer.parseInt(fileNumberStartNumberTextField.getText()),
                        filePaths
                );
            } else if (
                prefixRadioButton.isSelected() &&
                prefixSuffixDescendingRadioButton.isSelected()
            ) {
                return FileUtilities.numberPrependDesc(
                    fileNumberInputStringTextField.getText(),
                    Integer.parseInt(fileNumberStartNumberTextField.getText()),
                    filePaths
                );
            } else if (
                suffixRadioButton.isSelected() &&
                prefixSuffixDescendingRadioButton.isSelected()
            ) {
                return FileUtilities.numberAppendDesc(
                    fileNumberInputStringTextField.getText(),
                    Integer.parseInt(fileNumberStartNumberTextField.getText()),
                    filePaths
                );
            }
        }
        throw new RuntimeException("Impossible file combination was run.");
    }

    private Stream<String> getFilePathList() {
        return currentFiles.stream().map(File::getAbsolutePath);
    }

    private static void eraseTable(javax.swing.JTable table) {
        while (table.getModel().getRowCount() > 0)
            ((DefaultTableModel) table.getModel()).removeRow(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser c;
    private javax.swing.JLabel fileNumberInputStringLabel;
    private javax.swing.JTextField fileNumberInputStringTextField;
    private javax.swing.JLabel fileNumberStartNumberLabel;
    private javax.swing.JTextField fileNumberStartNumberTextField;
    private javax.swing.JTable filePreviewTable;
    private javax.swing.JPanel fileRenamePanel;
    private javax.swing.JLabel fileRenameReplaceLabel;
    private javax.swing.JTextField fileRenameTextField;
    private javax.swing.JButton filesClearButton;
    private javax.swing.JButton filesOpenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable loadedFileTable;
    private javax.swing.JRadioButton prefixRadioButton;
    private javax.swing.JRadioButton prefixSuffixAscendingRadioButton;
    private javax.swing.ButtonGroup prefixSuffixButtonGroup;
    private javax.swing.JRadioButton prefixSuffixDescendingRadioButton;
    private javax.swing.ButtonGroup prefixSuffixNumberButtonGroup;
    private javax.swing.JCheckBox prefixSuffixNumberCheckBox;
    private javax.swing.JButton previewButton;
    private javax.swing.JTable previewFileTable;
    private javax.swing.JRadioButton renameAscendingRadioButton;
    private javax.swing.JButton renameButton;
    private javax.swing.JRadioButton renameDescendingRadioButton;
    private javax.swing.ButtonGroup renameNumberButtonGroup;
    private javax.swing.JSpinner renameTabStartingNumber;
    private javax.swing.JTabbedPane renameTabs;
    private javax.swing.JRadioButton suffixRadioButton;
    // End of variables declaration//GEN-END:variables
}
